apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-backstage
  annotations:
    github.com/project-slug: pynsuphasueb/hello-backstage
  tags:
    - sky
spec:
  type: other
  lifecycle: unknown
  owner: guests
